### ISSUE TITLE
remotely programming  

### ISSUE THREAD

**Issue by andre-pt** [CONTROLLINO-PLC/CONTROLLINO_Library#14]
Is there any way to program the controllino over ethernet?
I have my controllinos connected to my internal network and I would like to script updates without having physical access to them.
thanks

**Comment by CONTROLLINO-Support** [comment]
There exists Ariadne solution - programming via TFTP. Please see [issue and solution here](https://github.com/CONTROLLINO-PLC/CONTROLLINO_Library/issues/13)

**Comment by CONTROLLINO-Support** [comment]
Hi,
it is not so risky. You can always go back to the original CONTROLLINO bootloader. You can find them [here](https://github.com/CONTROLLINO-PLC/CONTROLLINO_Library/tree/master/Bootloaders) including a howto.
