### ISSUE TITLE
Controllino Mega Digital Pin 20 to 23

### ISSUE THREAD

**Issue by TiEr92** [CONTROLLINO-PLC/CONTROLLINO_Library#16]
Hi, 
how can i change the state of the pins mentioned in the title? Is it only possible with port manipulation? 

Is there a way to add these pins to the library?

greetings

**Comment by CONTROLLINO-Support** [comment]
Hi,
please check our example sketch File->Examples->CONTROLLINO->MEGA->PortManipulation_MAXI_MEGA .
Enjoy!

**Comment by CONTROLLINO-Support** [comment]
Fixed with BSP 3.0.1 - all CONTROLLINO pins have their Arduino numbers.

**Comment by marcelwolter** [comment]
Where can I find the Arduino numbers for Digital Pins 20 to 23 (Controllino MEGA)? As you mentioned all Controllino pins have their Arduino numbers since BSP 3.0.1, but in the official pinout table (v. 1.1) the numbers are missing. Thanks!

**Comment by CONTROLLINO-Support** [comment]
PD4 - CONTROLLINO MEGA Digital 20 is now pin 77
PD5 - CONTROLLINO MEGA Digital 21 is now pin 78
PD6 - CONTROLLINO MEGA Digital 22 is now pin 79
PJ4 - CONTROLLINO MEGA Digital 23 is now pin 80

Sorry, the pinout table was not updated yet.

**Comment by marcelwolter** [comment]
Great, thanks a lot! This information really helps 😀
