### ISSUE TITLE
installation error Controllino boards

### ISSUE THREAD

**Issue by dadoblu2000** [CONTROLLINO-PLC/CONTROLLINO_Library#17]
I'm trying to install CONTROLLINO but this error is returned how can I solve it?
![error_controllino_download_board](https://user-images.githubusercontent.com/40566527/41848396-a04210c8-787d-11e8-978c-f1032c06a5ef.PNG)

**Comment by CONTROLLINO-Support** [comment]
Is it the first time you are installing CONTROLLINO? Or is there a possibility that you have some old version of the CONTROLLINO installed already? Thanks!

**Comment by dadoblu2000** [comment]
thanks for the quick reply, first time

**Comment by dadoblu2000** [comment]
I downloaded the installation guide of the librinomaxi libraries and managed to correctly configure arduino 1.8.5
This topic can be closed thanks

**Comment by dadoblu2000** [comment]
I downloaded the installation guide of the controllino libraries and managed to correctly configure arduino 1.8.5
This topic can be closed thanks

**Comment by CONTROLLINO-Support** [comment]
Great! Thanks!

**Comment by CONTROLLINO-Support** [comment]
Error with downloading of the BSP zip file, or with wrong CRC checksum of the file are time to time reported. But during our testing we have found that it is enough to try to install it e.g. 5 times and then it works. It seems to be an issue between Arduino IDE and GitHub.
