### ISSUE TITLE
UPGRADE TO NEW BSP VERSION 3.0.1 AVAILABLE

### ISSUE THREAD

**Issue by apetitjean** [CONTROLLINO-PLC/CONTROLLINO_Library#22]
Hi there,

I'm pretty noob in the Controllino's world and pardon my ignorance but what BSP stands for?

How can determine my current BSP version number and how can I upgrade?

Thanks in advance.

**Comment by CONTROLLINO-Support** [comment]
![01_properties](https://user-images.githubusercontent.com/24877193/45161030-2c17fa80-b1eb-11e8-8bee-4b167e996d1e.jpg)
![02_boardsmanager](https://user-images.githubusercontent.com/24877193/45161038-2f12eb00-b1eb-11e8-8b70-82c0ec976142.jpg)
![03_bsp](https://user-images.githubusercontent.com/24877193/45161042-31754500-b1eb-11e8-9238-67ea4e0378b2.jpg)

**Comment by apetitjean** [comment]
Awesome! Thank you very much. 

And what about the meaning of BSP?

**Comment by CONTROLLINO-Support** [comment]
Hi! You are welcome!

BSP means Board Support Package.

Enjoy your CONTROLLINO! :-)

**Comment by apetitjean** [comment]
Ah!! This is clearer now! :)

Thanks
