### ISSUE TITLE
Board Library

### ISSUE THREAD

**Issue by gators54** [CONTROLLINO-PLC/CONTROLLINO_Library#28]
![capture2](https://user-images.githubusercontent.com/17939748/49176192-e1041400-f30f-11e8-9037-16db0f467fe4.PNG)

I am having trouble getting the board library to load. Everything else is installed properly.

Thanks.

**Comment by gators54** [comment]
Yes i did and it worked. This is the link I am using.

https://raw.githubusercontent.com/CONTROLLINO-PLC/CONTROLLINO_Library/master/Boards/package_ControllinoHardware_index.json

**Comment by gators54** [comment]
![24](https://user-images.githubusercontent.com/17939748/49392365-d2dd3b80-f6f3-11e8-92ba-49254ae3f1d1.PNG)

**Comment by CONTROLLINO-Support** [comment]
Then something seems to wrong at your side. Because you should see this:
![controllino_json](https://user-images.githubusercontent.com/24877193/49439531-91b35d00-f7c1-11e8-984a-4a6e67a52da8.jpg)

**Comment by gators54** [comment]
![3](https://user-images.githubusercontent.com/17939748/49449537-b814d080-f7a0-11e8-8ee5-27793581a99d.PNG)

Sorry, that was the file from the preference folder showing. I get the same thing you do in the browser. I've tried a few different things and still no luck.

**Comment by CONTROLLINO-Support** [comment]
Hello, another user has reported the same issue and finally the root cause was some additional space in the URL, or maybe before or after the URL.
