### ISSUE TITLE
Wrong pin ID in for screw terminals of MINI's relays

### ISSUE THREAD

**Issue by sumpfralle** [CONTROLLINO-PLC/CONTROLLINO_Library#30]
I am using a MINI device.

In order to use two of the relays, I had to overwrite two defines:
```
#define CONTROLLINO_SCREW_TERMINAL_RELAY_00 4                                                       
#define CONTROLLINO_SCREW_TERMINAL_RELAY_02 6                                                       
```

The original values seem to be:
```
#define CONTROLLINO_SCREW_TERMINAL_RELAY_00 8
#define CONTROLLINO_SCREW_TERMINAL_RELAY_02 4
```

Or maybe I am just misinterpreting the pinout or the labeling?
I would be glad, if you could verify this.

**Comment by CONTROLLINO-Support** [comment]
Oops! You are right! I am going to fix ...

Thanks for the report!

**Comment by CONTROLLINO-Support** [comment]
Fixed. Thread to be closed when the new version of the library will be released.

**Comment by sumpfralle** [comment]
ping?

**Comment by CONTROLLINO-Support** [comment]
We were still waiting for some other stuff to do not release a new version for each small bugfix. But you are right, time is over :)

**Comment by CONTROLLINO-Support** [comment]
[Done! Thanks!](https://github.com/CONTROLLINO-PLC/CONTROLLINO_Library/releases)
