### ISSUE TITLE
Connect Bluetooth to Controllino

### ISSUE THREAD

**Issue by Keiser615** [CONTROLLINO-PLC/CONTROLLINO_Library#33]
Hi

Is posible tu use the HC-05 Bluetooth module on the Controllino Platform?

**Comment by Keiser615** [comment]
Hey

We are making a great project and we need your help anybody knows how is the communication between the HC-05 bluetooth module?

**Comment by CONTROLLINO-Support** [comment]
Hi, may I ask you to share with us how do you interconnect the CONTROLLINO and the HC-05, please? Schematics drawing, photo?

**Comment by ssozonoff** [comment]
What was the outcome of this quesiton ? Possible to get bluetooth connectivity with a Controllino ?
