### ISSUE TITLE
SPI & I2C on mini pure ?

### ISSUE THREAD

**Issue by catx23** [CONTROLLINO-PLC/CONTROLLINO_Library#38]
Hi,
the mini pure io reference says it has SPI and I2C but which pins I have to use ? Also there is no pin layout picture for the pure,...
thanks.

**Comment by CONTROLLINO-Support** [comment]
Hi, I am sorry, but this was a mistake in the description of the product. These interfaces are only accessible via pin header which is missing on the pure variants of CONTROLLINOs. We have fixed that on the web pages.
