### ISSUE TITLE
Wrong pins assignment in Controllino.h

### ISSUE THREAD

**Issue by Uskok** [CONTROLLINO-PLC/CONTROLLINO_Library#44]
Hi,

The pins are wrong assigned inside Controllino.h for MEGA

Wrong:
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_16 **18**
  #define CONTROLLINO_PIN_HEADER_INT_00 18
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_16 **18**
  #define CONTROLLINO_SCREW_TERMINAL_INT_00 18
  
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_17 **19**
  #define CONTROLLINO_PIN_HEADER_INT_01 19
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_17 **19**
  #define CONTROLLINO_SCREW_TERMINAL_INT_01 19
  
  **Correct:**
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_16 38
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_16 38
   
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_17 39
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_17 39
  
#define CONTROLLINO_PIN_HEADER_DIGITAL_IN_18 40
#define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_18 40

 #define CONTROLLINO_PIN_HEADER_INT_00 18
 #define CONTROLLINO_SCREW_TERMINAL_INT_00 18

 #define CONTROLLINO_PIN_HEADER_INT_01 19
 #define CONTROLLINO_SCREW_TERMINAL_INT_01 19

**Comment by CONTROLLINO-Support** [comment]
Hi,

yes, you are right! Thanks for the information. We will fix it soon.

Best regards,
Lukas

**Comment by JasekJiri** [comment]
Hello

The Controllino.h is fixed.
Each new installation will include this fix, and when a new release is released, all libraries will be updated.

Best Regards
Jiri Jasek
