### ISSUE TITLE
vscode+PlatformIO does not flash when delay(variableName) is used. delay(100) works.

### ISSUE THREAD

**Issue by greenveg** [CONTROLLINO-PLC/CONTROLLINO_Library#48]
This code compiles but does not flash:
```
#include <Arduino.h>
#include <Controllino.h>  

unsigned long valveCycleTime = 20;

void setup() {  
  pinMode(CONTROLLINO_D0, OUTPUT);
  
  digitalWrite(CONTROLLINO_D0, HIGH);   
  delay(valveCycleTime);                                          //THIS IS THE PROBLEMATIC LINE    
  digitalWrite(CONTROLLINO_D0, LOW);    
  delay(100);   
}

void loop() {}
```

When changed to `delay(100)` it compiles and flashes no problem.

Using `int` or `uint32_t` does not seem to matter.

**Comment by CONTROLLINO-Support** [comment]
Hello, I have tried the same code with Arduino IDE and CONTROLLINO MAXI and it works fine.

Which variant of CONTROLLINO do you have?

Thanks,
Lukas

**Comment by greenveg** [comment]
Older MINI. 
Will try with a freshly bought MAXI tomorrow!

**Comment by pmmarquez** [comment]
This is definitely working without issue
