### ISSUE TITLE
Controllino boards not found 

### ISSUE THREAD

**Issue by edmsNG** [CONTROLLINO-PLC/CONTROLLINO_Library#49]
Hello,
I have an issue with instaling Controllino boards on Arduino IDE. I did all steps that are required (install Controllino library, paste URL in Preferences), but when I open Board Manager and type in search CONTROLLINO nothing shows up. Does anyone have any idea why and how can I fix this?

![image](https://user-images.githubusercontent.com/95345911/144211858-6ee5d022-6e6f-48fe-838b-37707a9a1ac9.png)

**Comment by CONTROLLINO-Support** [comment]
Hello, please double check the URL link. Maybe there are some whitespaces there?

It works fine at my side

![image](https://user-images.githubusercontent.com/24877193/144214810-8074850d-a4ed-4e9b-b1af-151a4c523583.png)

**Comment by edmsNG** [comment]
Hello,
Thank you for quick response. I duble checked. I pasted in this: https://raw.githubusercontent.com/CONTROLLINO-PLC/CONTROLLINO_Library/master/Boards/package_ControllinoHardware_index.json
and still no luck. Is this URL corect? 
Are there some aditional settings that I need to change?

![image](https://user-images.githubusercontent.com/95345911/144229209-a0afc414-6dcf-4147-962f-e3759171c6e7.png)

**Comment by CONTROLLINO-Support** [comment]
No, it should work Out-of-the-box and yes, the URL is correct.
