### ISSUE TITLE
How to get JTAG working with Controllino Maxi

### ISSUE THREAD

**Issue by Fuzzyma** [CONTROLLINO-PLC/CONTROLLINO_Library#5]
I know how to connect my ATmel-Ice to get ISP working on the Controllino. However, connecting to the JTAG Pins with JTAG-Fuse enabled and BOOTRST Fuse disabled is not working.

Is there a way to use JTAG with the Controllino Hardware?

**Comment by CONTROLLINO-Support** [comment]
You are correct - due to protection serial resistors on the pin header signals the JTAG does not work. I am afraid that is it not possible to use JTAG with CONTROLLINO.

**Comment by Fuzzyma** [comment]
What about debug wire? Is it possible with SPI on Controllino?

**Comment by CONTROLLINO-Support** [comment]
I am afraid that there will be the same problem with DebugWIRE as is on Arduino boards - the 100nF capacitor between Atmega16U2 and the main Atmega controller. Please see this article https://awtfy.com/2010/02/21/modify-an-arduino-for-debugwire/ .So, the only way is to disassemble the device and remove the capacitor. Is that a potential way for you?

**Comment by Fuzzyma** [comment]
No unfortunately not :/

**Comment by CONTROLLINO-Support** [comment]
We are pretty close to release a new generation of CONTROLLINO - https://controllino.biz/controllino-myplc/ It has the JTAG accessible from outside. ;-)
