### ISSUE TITLE
RS485 ModbusRTU Reboot

### ISSUE THREAD

**Issue by orichienal** [CONTROLLINO-PLC/CONTROLLINO_Library#51]
Hello folks,
I had programmed something with rs485 and modbusRTU some time ago and just wanted to use it again.
Unfortunately without success. 
Each time the Controllino (slave) is asked, it reboots. (Detection through an output in the setup and in the loop)
Then I copied the example (second one modbusRTU) on the website with two Controllino with the same result.
Has anyone experienced something similar or can someone help me.

Here is the example (second one)(first one works fine):
https://www.controllino.com/knowledge-base/rs485-modbusrtu/

Many thanks and greetings
orichienal

**Comment by pmmarquez** [comment]
@orichienal please try the Modbus examples within the library.
