### ISSUE TITLE
Add important pin definitions to Controllino.h

### ISSUE THREAD

**Issue by pmmarquez** [CONTROLLINO-PLC/CONTROLLINO_Library#61]
There are some some important pins not present in ***Controllino.h*** that simplify some examples and library functions that are currently made with register manipulation, this pins are available in the BSP pin definitions: hardware/avr/VERSION/variants/Controllino_mega/pins_arduino.h
```
  PE  , // PE 6 ** 71 ** CONTROLLINO ETHERNET INTERRUPT
  PJ  , // PJ 7 ** 73 ** CONTROLLINO RTC INTERRUPT
  PE  , // PE 7 ** 74 ** CONTROLLINO OVERLOAD
  PJ  , // PJ 6 ** 75 ** CONTROLLINO RS485 DE
  PJ  , // PJ 5 ** 76 ** CONTROLLINO RS485 /RE
  PD  , // PD 4 ** 77 ** CONTROLLINO MEGA Digital 20
  PD  , // PD 5 ** 78 ** CONTROLLINO MEGA Digital 21
  PD  , // PD 6 ** 79 ** CONTROLLINO MEGA Digital 22
  PJ  , // PJ 4 ** 80 ** CONTROLLINO MEGA Digital 23
```

**Comment by CONTROLLINO-Support** [comment]
All necessary pin definitions are already there, like these
`#define CONTROLLINO_ETHERNET_CHIP_SELECT 70
  #define CONTROLLINO_ETHERNET_INTERRUPT 71
  #define CONTROLLINO_RTC_CHIP_SELECT 72
  #define CONTROLLINO_RTC_INTERRUPT 73
  #define CONTROLLINO_OVERLOAD 74
  #define CONTROLLINO_RS485_DE 75
  #define CONTROLLINO_RS485_nRE 76`
Issue to be closed.
