### ISSUE TITLE
Add to BSP external libraries

### ISSUE THREAD

**Issue by CONTROLLINO-Support** [CONTROLLINO-PLC/CONTROLLINO_Library#65]
Add these libraries into the BSP to freeze their latest versions
- Arduino RS485
- Arduino Modbus
- Controllino

**Comment by pmmarquez** [comment]
Partially complete with #71

**Comment by CONTROLLINO-Support** [comment]
Let´s keep the CONTROLLINO Library as a separate item as it is described in the CONTROLLINO Manual.
