### ISSUE TITLE
Add documentation about Ethernet

### ISSUE THREAD

**Issue by Vayel** [CONTROLLINO-PLC/CONTROLLINO_Library#9]
I bought a Controllino MAXI and I had difficulties connecting through Ethernet. `Ethernet.localIP()` always returned `255.255.255.255`.

The problem was due to the fact that Arduino IDE linked the standard Ethernet library and not Controllino's one (it appeared in the compilation logs of Arduino IDE). Under ArchLinux, I manually replaced `~/Arduino/libraries/Ethernet` by Controllino's Ethernet folder (`~/.arduino15/packages/CONTROLLINO_Boards/hardware/avr/2.0.1/libraries/Ethernet/src`) and it worked.

You may complete the [Learning](https://controllino.biz/controllino/learning/) page with such a procedure.

**Comment by CONTROLLINO-Support** [comment]
Thank you for the report and for the solution. As it seems to be an issue only on the ArchLinux, I will add it to the FAQ section.
